package interfaz;

import vistas.VistaContrasenia_establecida;
import vistas.VistaVerificacion_contrasenia_cambiada;

public class Contrasenia_restablecida extends VistaVerificacion_contrasenia_cambiada{
	public Establecer_nueva_contrasenia _establecer_nueva_contrasenia;
}