package fernandezmora.interfaz;

import vistas.VistaAdministrar_productos_anadidos;

public class Administrar_productos_anadidos extends VistaAdministrar_productos_anadidos{
	public Productos_listado_administracion _productos_listado_administracion;
}